import type { Metadata } from 'next';
import { Instrument_Sans } from 'next/font/google';
import './globals.css';
import classNames from 'classnames';
import AuthProvider from '@/context/auth-provider';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';
import ReduxProvider from '@/context/redux/redux-provider';
import store from '@/context/redux/store';

const instrunemt = Instrument_Sans({
  subsets: ['latin'],
  variable: '--font-instrument-sans',
});

export const metadata: Metadata = {
  title: 'Frontend Mentor | Link-sharing app',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClassName = classNames(instrunemt.className, 'bg-white-light');
  const session = await getServerSession(authOptions);

  return (
    <html lang='en'>
      <body className={bodyClassName}>
        <AuthProvider session={session}>
          <ReduxProvider store={store}>{children}</ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
