import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import classNames from "classnames";

const instrunemt = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-instrument-sans",
});

export const metadata: Metadata = {
  title: "Frontend Mentor | Link-sharing app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClassName = classNames(instrunemt.className, "bg-white-light");

  return (
    <html lang="en">
      <body className={bodyClassName}>{children}</body>
    </html>
  );
}
